/*
 * Akto_nayan
 * Akto generated openAPI file
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akto.mcp.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.ai.tool.annotation.ToolParam;

@Data
@NoArgsConstructor
public class CreateJiraIssueRequestJiraMetaData {

    @ToolParam(required=false)
    private String issueUrl;

    @ToolParam(required=false)
    private String hostStr;

    @ToolParam(required=false)
    private String issueTitle;

    @ToolParam(required=false)
    private TestingIssueId testingIssueId;

    @ToolParam(required=false)
    private String endPointStr;

    @ToolParam(required=false)
    private String issueDescription;
}
