/*
 * Akto_nayan
 * Akto generated openAPI file
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akto.mcp.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.ai.tool.annotation.ToolParam;

@Data
@NoArgsConstructor
public class FetchAffectedEndpointsRequestIssueId {

    @ToolParam(required=false)
    private String testSubCategory;

    @ToolParam(required=false)
    private String testErrorSource;

    @ToolParam(required=false)
    private String testCategoryFromSourceConfig;

    @ToolParam(required=false)
    private ApiInfoKey apiInfoKey;

    @ToolParam(required=false)
    private String testSourceConfig;
}
