/*
 * Akto_nayan
 * Akto generated openAPI file
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akto.mcp.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.akto.mcp.model.ModifyTestingRunConfigRequestEditableTestingRunConfigAutoTicketingDetails;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.ai.tool.annotation.ToolParam;

@Data
@NoArgsConstructor
public class ModifyTestingRunConfigRequestEditableTestingRunConfig {

    @ToolParam(required=false)
    private Boolean continuousTesting;

    @ToolParam(required=false)
    private ModifyTestingRunConfigRequestEditableTestingRunConfigAutoTicketingDetails autoTicketingDetails;

    @ToolParam(required=false)
    private Boolean sendMsTeamsAlert;

    @ToolParam(required=false)
    private List<String> testSubCategoryList;

    @ToolParam(required=false)
    private Integer maxConcurrentRequests;

    @ToolParam(required=false)
    private Boolean recurringDaily;

    @ToolParam(required=false)
    private String overriddenTestAppUrl;

    @ToolParam(required=false)
    private Boolean sendSlackAlert;

    @ToolParam(required=false)
    private Integer scheduleTimestamp;

    @ToolParam(required=false)
    private Boolean recurringWeekly;

    @ToolParam(required=false)
    private Integer testRunTime;

    @ToolParam(required=false)
    private String testingRunHexId;

    @ToolParam(required=false)
    private Boolean recurringMonthly;

    @ToolParam(required=false)
    private String testRoleId;
}
