/*
 * Akto_nayan
 * Akto generated openAPI file
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akto.mcp.models;

import java.util.List;
import java.util.Map;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.ai.tool.annotation.ToolParam;

@Data
@NoArgsConstructor
public class RetrieveAllCollectionTestsRequest {

    private String searchString;
    private String sortKey;
    private Integer sortOrder;
    private Integer limit;
    private Integer skip;
    private Map<String, List> filters;

    @ToolParam(description = "this is an epoch time in seconds. must be current timestamp")
    private Integer endTimestamp;

    @ToolParam(required = false, description = "Type of testing run. If not null then values must be anyone from ONE_TIME, RECURRING, CI_CD, CONTINUOUS_TESTING")
    private String testingRunType;

    @ToolParam(description = "this is an epoch time in seconds.")
    private Integer startTimestamp;
}
